---

- name: Update apt cache
  hosts: oracl-inst
  become: true
  tasks:
    - name: Run apt update
      apt:
        update_cache: yes

    - name: Install packages
      apt:
        name:
          - zsh
          - tmux
          - wireguard
          - wireguard-tools
        state: latest
